"""db product

Revision ID: 58098fe2e9d3
Revises: d0db073cb6e5
Create Date: 2025-08-27 13:37:01.080069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58098fe2e9d3'
down_revision = 'd0db073cb6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
