"""update User Model

Revision ID: eddf20981d9e
Revises: 0aff1439e150
Create Date: 2025-08-27 22:36:33.926207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddf20981d9e'
down_revision = '0aff1439e150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updatedate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deletedate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('deletedate')
        batch_op.drop_column('updatedate')
        batch_op.drop_column('createdate')

    # ### end Alembic commands ###
